[package]
name = "aws-lambda-rust-benchmark"
version = "0.1.0"
authors = ["drluke"]
edition = "2018"

[dependencies]
lambda_runtime = "0.2.1"
serde = {version = "1.0.114"}
serde_json = "1.0.56"
simple_logger = "1.6.0"
log = "0.4.8"
aws_lambda_events = "^0.3.0"